### ISSUE TITLE
solana import mnemonic

### ISSUE THREAD

**Issue by s749312025** [robin0319/Multicoin-Transfer#1]
const solanaWeb3 = require('@solana/web3.js');
const nacl = require("tweetnacl")
const bip39 = require('bip39');

const ed25519 = require('ed25519-hd-key')

const bs58 = require("bs58")

const derivePath = "m/44'/501'/0'/0'"
const seed = bip39.mnemonicToSeedSync(mnemonic)
const derivedSeed = ed25519.derivePath(derivePath, seed.toString('hex')).key

console.log({seed, derivedSeed});
console.log(nacl.sign.keyPair.fromSeed(derivedSeed));  //account {publicKey, secretKey}
console.log(bs58.encode(nacl.sign.keyPair.fromSeed(derivedSeed).secretKey));  // pr

**Comment by masterdev0319** [comment]
Hi.
Thank you for your attention.
Are you gonna create new account on Solana?

**Comment by s749312025** [comment]
no 
By the way.😁

**Comment by s749312025** [comment]
becase mnemonic can creat many account, It is best to use derivePath.

**Comment by s749312025** [comment]
so
How should I get balance changes from transaction
